service: return-pdf
provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  profile: finovance
  stage: dev
functions:
  get-pdf:
    handler: get_pdf.handler
    events:
      - http:
          path: statements
          method: get
custom:
  apigwBinary:
    #list of mime-types
    types: 
      - '*/*'
plugins:
  - serverless-apigw-binary
